version: '3.8'

services:
  db:
    image: postgres:13.10
    environment:
      - POSTGRES_USER=foodgram_user
      - POSTGRES_PASSWORD=foodgram_password
      - POSTGRES_DB=foodgram
    volumes:
      - pg_database:/var/lib/postgresql/data
    restart: always
    networks:
      - foodgram-network

  backend:
    image: ximikat01/foodgram_backend:latest
    env_file: .env
    command: sh -c "python manage.py collectstatic --noinput && gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      - db
    restart: always
    networks:
      - foodgram-network

  frontend:
    image: ximikat01/foodgram_frontend:latest
    command: sh -c "cp -r /app/build/. /usr/share/nginx/html/ && tail -f /dev/null"
    volumes:
      - static:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - foodgram-network

  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - "80:80"
      - "443:443"  # Добавлено для HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/usr/share/nginx/html
      - media:/usr/share/nginx/html/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - foodgram-network

volumes:
  pg_database:
  static:
  media:

networks:
  foodgram-network:
    driver: bridge