services:
  db:
    image: postgres:13.10
    environment:
      - POSTGRES_USER=foodgram_user
      - POSTGRES_PASSWORD=foodgram_password
      - POSTGRES_DB=foodgram
    volumes:
      - pg_database:/var/lib/postgresql/data
    restart: always

  backend:
    image: ximikat01/foodgram_backend:latest
    env_file: .env
    command: sh -c "python manage.py collectstatic --noinput && gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      - db
    restart: always

  frontend:
    image: ximikat01/foodgram_frontend:latest
    command: sh -c "cp -r /app/build/. /usr/share/nginx/html/"
    volumes:
      - static:/usr/share/nginx/html
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/usr/share/nginx/html
      - media:/usr/share/nginx/html/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
    restart: always

volumes:
  pg_database:
  static:
  media: